import moment from "moment";
import React, { useEffect, useState } from "react";
import { Dimensions, Image, StyleSheet, Text, View } from "react-native";
import { ContributionGraph } from "react-native-chart-kit";
import tw from "tailwind-react-native-classnames";
import PolarBear from "../../assets/polar-bear.png";
import Loading from "../../components/Loading";
import firebase from "../../config/firebaseConfig";
import { useAuth } from "../../contexts/authContext";
import { colors, fonts } from "../../styles/global";

const Stats = () => {
  const [selectedData, setSelectedData] = useState(null);
  const [powerData, setPowerData] = useState(null);

  const { currentUser } = useAuth();

  useEffect(() => {
    let db = firebase.firestore();
    db.collection("powerData")
      .where("user", "==", currentUser.uid)
      .onSnapshot((snapshot) => {
        setPowerData(
          snapshot.docs.map((doc) => ({
            date: `${doc.data().date.slice(0, 4)}-${doc
              .data()
              .date.slice(4, 6)}-${doc.data().date.slice(6, 8)}`,
            count: doc.data().power,
          }))
        );
      });
  }, [currentUser]);

  // console.log(powerData)

  return (
    <View
      style={tw.style(` flex h-full`, {
        backgroundColor: colors.bg1,
      })}
    >
      <Text
        style={tw.style("text-lg mx-8 mb-4 mt-4", {
          fontFamily: fonts.semibold,
          color: colors.text1,
        })}
      >
        Summary of Energy Generated by Your Solar Panel:
      </Text>
      {powerData ? (
        <ContributionGraph
          values={powerData}
          endDate={new Date(new Date())}
          numDays={105}
          width={Dimensions.get("window").width}
          height={220}
          chartConfig={chartConfig}
          onDayPress={(value) => {
            setSelectedData(value);
          }}
        />
      ) : (
        <Loading />
      )}
      
      <View style={tw.style("p-4 mx-8 rounded-lg bg-gray-700 mt-12", {})}>
        <Image
          source={PolarBear}
          style={tw.style("w-16 h-16 z-50 absolute right-10 top-4")}
        />
        <Text
          style={tw.style("text-gray-200", {
            fontFamily: fonts.semibold,
            fontSize: 16,
          })}
        >
          {!selectedData?.count ? "1 kW-hr " : `On ${moment(selectedData.date).format("DD/MM/YYYY")}, you `}reduce{" "}
        </Text>
        <Text
          style={tw.style("text-2xl my-2", {
            color: colors.text1,
            fontFamily: fonts.bold,
          })}
        >
          {selectedData?.count>0 ? parseFloat(0.92*selectedData.count).toFixed(2) : 0.92} lb
        </Text>
        <Text style={tw.style("text-gray-300", { fontFamily: fonts.regular })}>
          off your daily carbon footprint. If you want to do something good for
          the planet reduce your carbon footprint. The polar bears will thank
          you.
        </Text>
      </View>

    </View>
  );
};

export default Stats;

const chartConfig = {
  backgroundGradientFrom: colors.bg2,
  backgroundGradientFromOpacity: 1,
  backgroundGradientTo: colors.bg2,
  backgroundGradientToOpacity: 1,
  color: (opacity = 1) => `rgba(255, 255, 255, ${opacity || 1})`,
  strokeWidth: 2, // optional, default 3
  barPercentage: 0.5,
  useShadowColorFromDataset: false, // optional
};

const styles = StyleSheet.create({});
